-- Insert sample Akashic Records data
INSERT INTO records (id, created_at, updated_at, title, category, content, timestamp, cosmic_level) VALUES
('1', '2024-01-15T10:30:00Z', '2024-01-15T10:30:00Z', 'The Genesis of Consciousness', 'cosmic', 'In the beginning, there was only the void, and from the void emerged the first spark of consciousness. This primordial awareness, pure and undifferentiated, began to explore itself, creating the first ripples in the cosmic fabric of existence. Each thought, each moment of awareness, was recorded in the eternal memory of the universe, forming the foundation of what we now call the Akashic Records.', '2024-01-15T10:30:00Z', 9),
('2', '2024-01-14T15:45:00Z', '2024-01-14T15:45:00Z', 'The Eternal Dance of Galaxies', 'astronomy', 'Across the vast expanse of space, galaxies spiral in an eternal dance, each movement recorded in the cosmic memory. The gravitational waves created by these celestial bodies carry information about the very fabric of spacetime itself. Every collision, every merger, every birth of a new star is etched into the universal consciousness, creating a symphony of cosmic proportions.', '2024-01-14T15:45:00Z', 8),
('3', '2024-01-13T09:20:00Z', '2024-01-13T09:20:00Z', 'The Akashic Resonance', 'spiritual', 'Every soul carries within it a unique frequency, a resonance that echoes through the Akashic Records. This vibrational signature contains the complete history of that soul''s journey through time and space. When souls connect, their frequencies harmonize, creating new patterns in the cosmic tapestry that are forever preserved in the eternal archive.', '2024-01-13T09:20:00Z', 10),
('4', '2024-01-12T14:15:00Z', '2024-01-12T14:15:00Z', 'The Cosmic Web of Knowledge', 'cosmic', 'Interconnected threads of wisdom span across dimensions, forming a vast web that connects all knowledge in the universe. Each node in this web represents a moment of understanding, a breakthrough in consciousness, or a discovery that expands the boundaries of what is known. The Akashic Records serve as the central hub of this cosmic information network.', '2024-01-12T14:15:00Z', 9),
('5', '2024-01-11T11:30:00Z', '2024-01-11T11:30:00Z', 'The Quantum Memory Field', 'astronomy', 'At the quantum level, information is preserved in the very fabric of spacetime. Every particle, every wave, every interaction leaves an imprint in the quantum field. These imprints form a vast memory system that records every event in the universe, from the birth of stars to the thoughts of conscious beings.', '2024-01-11T11:30:00Z', 7),
('6', '2024-01-10T16:45:00Z', '2024-01-10T16:45:00Z', 'The Soul''s Journey Through Time', 'spiritual', 'Each soul embarks on a journey through countless lifetimes, accumulating experiences, wisdom, and growth. The Akashic Records contain the complete chronicle of these journeys, preserving not just the events but the lessons learned, the love shared, and the consciousness expanded through each incarnation.', '2024-01-10T16:45:00Z', 8),
('7', '2024-01-09T13:20:00Z', '2024-01-09T13:20:00Z', 'The Universal Library', 'historical', 'Imagine a library so vast that it contains every book ever written, every story ever told, every experience ever lived. The Akashic Records are this universal library, where every moment of existence is carefully cataloged and preserved for eternity. Scholars of consciousness can access this infinite repository of knowledge.', '2024-01-09T13:20:00Z', 6),
('8', '2024-01-08T08:15:00Z', '2024-01-08T08:15:00Z', 'The Cosmic Symphony', 'cosmic', 'The universe is not silent but filled with a symphony of frequencies, vibrations, and harmonies. Each celestial body, each energy field, each conscious being contributes to this cosmic orchestra. The Akashic Records capture the full score of this universal symphony, preserving every note, every rhythm, every melody for all time.', '2024-01-08T08:15:00Z', 9),
('9', '2024-01-07T19:30:00Z', '2024-01-07T19:30:00Z', 'The Dimensional Gateway', 'spiritual', 'The Akashic Records exist beyond the limitations of three-dimensional space and linear time. They are accessible through dimensional gateways that connect the physical realm with higher planes of existence. Those who learn to navigate these gateways can access the infinite wisdom stored within the cosmic archive.', '2024-01-07T19:30:00Z', 10),
('10', '2024-01-06T12:00:00Z', '2024-01-06T12:00:00Z', 'The Eternal Now', 'cosmic', 'In the Akashic Records, past, present, and future exist simultaneously in an eternal now. Time is not a linear progression but a vast field of possibilities where all moments coexist. This timeless perspective allows for the complete understanding of cause and effect, karma and destiny, and the interconnected nature of all existence.', '2024-01-06T12:00:00Z', 9);